# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "e2e_test_no_updates")

load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
    "http_file",
)

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "01f1826346a828410666d69df1a748f3a5a3b33924b9369c25064a7a553b133a",
    strip_prefix = "rules_docker-f829974af764c60d57ef6630ea4b8499529d0093",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/f829974af764c60d57ef6630ea4b8499529d0093.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load("@io_bazel_rules_docker//container:container.bzl", "container_pull")
load(":revisions.bzl", "DEBS_TARBALL", "IMAGE")

container_pull(
    name = "fus_managed_ubuntu1604",
    digest = IMAGE.sha256,
    registry = "gcr.io",
    repository = "asci-toolchain/container_release_tools_e2e_tests/no_updates/ubuntu1604",
)

http_file(
    name = "image_debs",
    downloaded_file_path = DEBS_TARBALL.revision + "_image_debs.tar",
    sha256 = DEBS_TARBALL.sha256,
    urls = [
        "https://storage.googleapis.com/container_release_tools_e2e_tests/no_updates/debs/" + DEBS_TARBALL.revision + "_image_debs.tar",
    ],
)
