# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "ubuntu1404_bazel_docker_gcloud")

load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
    "http_file",
)

http_archive(
    name = "bazel_toolchains",
    sha256 = "91db7cf3a400da264e9123bb3d070e80184d9e40a87fc38b50e1dbb002b212fc",
    strip_prefix = "bazel-toolchains-db36179f00b0b252a80824ed7dabc636c5e6c5fe",
    urls = ["https://github.com/bazelbuild/bazel-toolchains/archive/db36179f00b0b252a80824ed7dabc636c5e6c5fe.tar.gz"],
)

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "4abb48f56b838957c9c72ac511b44f79612fcf39d08338fad14a8e3f6b0572ea",
    strip_prefix = "rules_docker-b8ff6a85ec359db3fd5657accd3e524daf12016d",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/b8ff6a85ec359db3fd5657accd3e524daf12016d.tar.gz"],
)

http_archive(
    name = "base_images_docker",
    sha256 = "ce6043d38aa7fad421910311aecec865beb060eb56d8c3eb5af62b2805e9379c",
    strip_prefix = "base-images-docker-7657d04ad9e30b9b8d981b96ae57634cd45ba18a",
    urls = ["https://github.com/GoogleContainerTools/base-images-docker/archive/7657d04ad9e30b9b8d981b96ae57634cd45ba18a.tar.gz"],
)

http_archive(
    name = "layer_definitions",
    sha256 = "cf84d88a909c25cabe5c25eac99de286b81137c14e5b87f3dffc58251d10c302",
    strip_prefix = "layer-definitions-58707de8484817bebbee0a77eac6663fa4bf5dea",
    urls = ["https://github.com/GoogleCloudPlatform/layer-definitions/archive/58707de8484817bebbee0a77eac6663fa4bf5dea.tar.gz"],
)

http_archive(
    name = "bazel_skylib",
    # Commit c00ef493869e2966d47508e8625aae723a4a3054 of 2018-12-10
    sha256 = "7363ae6721c1648017e23a200013510c9e71ca69f398d52886ee6af7f26af436",
    strip_prefix = "bazel-skylib-c00ef493869e2966d47508e8625aae723a4a3054",
    urls = ["https://github.com/bazelbuild/bazel-skylib/archive/c00ef493869e2966d47508e8625aae723a4a3054.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load("@layer_definitions//layers/ubuntu1404/base:deps.bzl", ubuntu1404_base_deps = "deps")

ubuntu1404_base_deps()

load("@layer_definitions//layers/ubuntu1404/bazel:deps.bzl", bazel_deps = "deps")

bazel_deps()

load("@layer_definitions//layers/ubuntu1404/gcc:deps.bzl", gcc_deps = "deps")

gcc_deps()

load("@layer_definitions//layers/ubuntu1404/docker:deps.bzl", docker_deps = "deps")

docker_deps()

load("@layer_definitions//layers/ubuntu1404/gcloud:deps.bzl", gcloud_deps = "deps")

gcloud_deps()

load("@layer_definitions//layers/ubuntu1404/java:deps.bzl", java8_deps = "deps")

java8_deps()

load("@layer_definitions//layers/ubuntu1404/python:deps.bzl", python_deps = "deps")

python_deps()
