# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

NSJAIL_DEBS = struct(
    revision = "1572368889",
    sha256 = "14703eb827d328b0a85e3bf3c838583170f09942bba70db68915e3a92d18cf91",
)

RBE_IMAGE_DEBS = struct(
    revision = "1572370336",
    sha256 = "d1b38af6de19745750b45de1dcd09aba7912a52db5d5b40b286a8c88dd46617e",
)

GOOGLE_NSJAIL = struct(
    commit = "2ca90bf208bfdc0d64daa05c7bc42bd5a81ebde9",
    sha256 = "f2be69237b9ac1ee9a3ba3403e26dde4f2142cc924a008f1b23c07b4f89f9635",
)

RULES_DOCKER = struct(
    commit = "b97ba729728a37e86baefaf66691f733b4bdee19",
    sha256 = "5320f2ede348684109cbf4dc7de7d09b026f9bce8c04562e6bdc65e2eca72aac",
)

LAYER_DEFINITIONS = struct(
    commit = "a8dec8045d939293593458e8826c97418ec5ad63",
    sha256 = "6dfefabfb1fba181bbd11575db296326aa603ed6a84a85d1dd567b52e58cd56a",
)
