# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

NSJAIL_DEBS = struct(
    revision = "1600698800",
    sha256 = "4b78f7b97e5a64e50f5f86bb830928136c6eca7d3deaa6764281af1aea316b92",
)

RBE_IMAGE_DEBS = struct(
    revision = "1594060432",
    sha256 = "04c9e498b1e6b046fc539cf967f008e09ec68eeba50e2d4ba5e906d6cc28bb6d",
)

RULES_DOCKER = struct(
    commit = "faaa10a72fa9abde070e2a20d6046e9f9b849e9a",
    sha256 = "feb53c560be2f97b7d02b23a1738a3154ba89fe630f09a7a838dcad38731b0b8",
)

LAYER_DEFINITIONS = struct(
    commit = "51b2240979058d11dedde6d4f78bdb079fdeb57f",
    sha256 = "ada4535cb687605d6cb2aa9e2b70e715f6b7125a86702584fb1ef10e87d4e836",
)
