workspace(name = "chromium_linux_rbe")

load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
)
load(
    "//:revisions.bzl",
    "LAYER_DEFINITIONS",
    "RULES_DOCKER",
)

# Download the rules_docker repository.
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = RULES_DOCKER.sha256,
    strip_prefix = "rules_docker-" + RULES_DOCKER.commit,
    urls = ["https://github.com/bazelbuild/rules_docker/archive/" + RULES_DOCKER.commit + ".tar.gz"],
)

http_archive(
    name = "layer_definitions",
    sha256 = LAYER_DEFINITIONS.sha256,
    strip_prefix = "layer-definitions-" + LAYER_DEFINITIONS.commit,
    urls = ["https://github.com/GoogleCloudPlatform/layer-definitions/archive/" + LAYER_DEFINITIONS.commit + ".tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load("@layer_definitions//layers/ubuntu1604/base:deps.bzl", ubuntu1604_base_deps = "deps")

ubuntu1604_base_deps()

load("@layer_definitions//layers/ubuntu1604/docker:deps.bzl", docker_deps = "deps")

docker_deps()

load("@layer_definitions//layers/ubuntu1604/python:deps.bzl", python_deps = "deps")

python_deps()
