# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

IMAGE = struct(
    # sha256 = "invalid sha256 to be updated by DUS",
    sha256 = "sha256:ee02edbafda63080ecdea2a62f08104e0c04d51844d136d41c0e54e33feb3cdf",
)

BAZEL_INSTALLER = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "0.28.1",
    sha256 = "a2a7e4cb38d7bc774a5bbfab4d45293f5f2158eb6caf0128792cc1148732a4e6",
)

BAZEL_DEBS_TARBALL = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "1563980495",
    sha256 = "6071af0905610f879b2e63fdc66378ec12fbba5adaca5cd9c258f95d50e2ad56",
)

CLANG_INSTALLER = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "r366207",
    sha256 = "ab5ca3fa052cd164904bf1c2da143c23ca309194a33b98793f08d11b6c104c5b",
)

LIBCXX_INSTALLER = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "r366207",
    sha256 = "abffabe8993c9de015701c0ae9ef3999a748599145617450001fc80ffc39e2d7",
)

CLANG_DEBS_TARBALL = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "1565701281",
    sha256 = "a7317352d7e2cf737567081d11c3302398754a58b51fd15622f8900dc7d4080e",
)
