# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

IMAGE = struct(
    # sha256 = "invalid sha256 to be updated by DUS",
    sha256 = "sha256:ee02edbafda63080ecdea2a62f08104e0c04d51844d136d41c0e54e33feb3cdf",
)

BAZEL_INSTALLER = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "0.28.1",
    sha256 = "a2a7e4cb38d7bc774a5bbfab4d45293f5f2158eb6caf0128792cc1148732a4e6",
)

BAZEL_DEBS_TARBALL = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "1563980495",
    sha256 = "6071af0905610f879b2e63fdc66378ec12fbba5adaca5cd9c258f95d50e2ad56",
)

CLANG_INSTALLER = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "r366207",
    sha256 = "ab5ca3fa052cd164904bf1c2da143c23ca309194a33b98793f08d11b6c104c5b",
)

LIBCXX_INSTALLER = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "r366207",
    sha256 = "abffabe8993c9de015701c0ae9ef3999a748599145617450001fc80ffc39e2d7",
)

CLANG_DEBS_TARBALL = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "1565701281",
    sha256 = "a7317352d7e2cf737567081d11c3302398754a58b51fd15622f8900dc7d4080e",
)

DOCKER_DEBS_TARBALL = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "1566388205",
    sha256 = "5b5d9570ca8ce9fdc4bcfcef7237ef3fea79c4a004f3b3cee5631d4d6d7989a1",
)

GCLOUD_DEBS_TARBALL = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "1566388549",
    sha256 = "11464fad29516c0ef8324996b45d9933438e09bb168942bfc99ee44f9e530f07",
)

OPENJDK_INSTALLER = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "11.29.3-ca-jdk11.0.2/zulu11.29.3-ca-jdk11.0.2-linux_x64-allmodules-90755145cb6e6418584d8603cd5fa9afbb30aecc-1549209950",
    sha256 = "460d8a4f0c0204160b48086e341b22943c9cca471b195340e75b38ae9eb33c1c",
)

OPENJDK_SRC = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "11.31.11-ca-jdk11.0.3/zsrc11.31.11-jdk11.0.3",
    sha256 = "65afc25dd914a094e25b1f804160bb20849f923d9a4b7d989f885558922e8182",
)

JAVA_DEBS_TARBALL = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "1566392443",
    sha256 = "c87774305ea93862c9a397dfa31a0d8fc386d058b7373610b875bda41aa87d2d",
)

CACERTS = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "1566392443",
    sha256 = "3e2c2fa876f9cdf98375d782f0a79b2d0d9d84580f27da71badcde7dfce97365",
)

PYTHON_DEBS_TARBALL = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "1566390679",
    sha256 = "a65339a05b313cc338a21756b8b1bec68291abfa95273de7e557ff68e064f5a9",
)
