# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update serivce and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

UBUNTU1604_TAR = struct(
    revision = "20190222",
    sha256 = "3eee1b642f67c045b085ba8745d0c077216dac2c28e69481e021f46453649af9",
)

DEBS_TARBALL = struct(
    revision = "20190313",
    sha256 = "2464f48615d1359ef9876212a084d58f537dd8de58c5da382b654f216561158c",
)
