# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

RULES_DOCKER = struct(
    commit = "f1557ebc5381e2a662314e21585aa8080e9508be",
    sha256 = "ffd6ee22fceb7db4d6e6f75bf69ecf439da7500ec2969fc5d371d165ceb22e3f",
)

LAYER_DEFINITIONS = struct(
    commit = "2e8fcbf2c09b387ef8a12e7b889c1ef2407b002a",
    sha256 = "1c25b10810eb1283f0aa2dd8e8190e90753d753db2c17a049cdccf20cc73f140",
)
