# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

IMAGE = struct(
	sha256 = "invalid sha256 to be updated by DUS",
)

GO_INSTALLER = struct(
	revision = "invalid revision to be updated by DUS",
	sha256 = "invalid sha256 to be updated by DUS",
)

TEXT_FILE = struct(
    revision = "invalid revision to be replaced by DUS",
    sha256 = "invalid sha256 to be replaced by DUS",
)

DEBS_TARBALL = struct(
    revision = "invalid revision to be replaced by DUS",
    sha256 = "invalid sha256 to be replaced by DUS",
)

RULES_DOCKER = struct(
	commit = "invalid commit sha to be updated by DUS",
	sha256 = "invalid sha256 to be updated by DUS",
)
