# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

RULES_DOCKER = struct(
	# commit = "invalid commit sha to be updated by DUS",
	# sha256 = "invalid sha256 to be updated by DUS",
    commit = "f829974af764c60d57ef6630ea4b8499529d0093",
    sha256 = "01f1826346a828410666d69df1a748f3a5a3b33924b9369c25064a7a553b133a",
)

IMAGE = struct(
	# sha256 = "invalid sha256 to be updated by DUS",
    sha256 = "sha256:ee02edbafda63080ecdea2a62f08104e0c04d51844d136d41c0e54e33feb3cdf",
)

GO_INSTALLER = struct(
	# revision = "invalid revision to be updated by DUS",
	# sha256 = "invalid sha256 to be updated by DUS",
    revision = "1.12.9",
    sha256 = "ac2a6efcc1f5ec8bdc0db0a988bb1d301d64b6d61b7e8d9e42f662fbb75a2b9b",
)

TEXT_FILE = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "1221480000",
    sha256 = "9963ea5c11baad729c0a82b4977a06ad0f4d3439570e6b7805400f5bf8cca968",
)

DEBS_TARBALL = struct(
    # revision = "invalid revision to be replaced by DUS",
    # sha256 = "invalid sha256 to be replaced by DUS",
    revision = "1565723065",
    sha256 = "943069a2a0b01108afc6bee57c0a2bf8e457bd98102e37c336085e7a70adfa33",
)
