# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

IMAGE = struct(
    sha256 = "sha256:abfcd19f5148a57dccb5d8453b667fc3fb9d156ad78be549ab38e88d37664058",
)

PY3_IMAGE = struct(
    sha256 = "sha256:ac3293568e31f831a247a4437c995156b268abda2f0fa739a14063f07c6088b6",
)

CLANG_INSTALLER = struct(
    revision = "407ac2eb5f136af5ddd213b8bcca176481ec5198",
    sha256 = "6cff276b2b67fe42011033ff40abbf4498fa1e6619963d3e642012ef86938abb",
)

LIBCXX_INSTALLER = struct(
    revision = "407ac2eb5f136af5ddd213b8bcca176481ec5198",
    sha256 = "ff9367e11db111c510070f133dcb6e5cab4c231b38f0068d000c4cadc1669e09",
)

CLANG_DEBS_TARBALL = struct(
    revision = "1575360273",
    sha256 = "1be7b541dc1e27a0ae0d32fe8eb8051db91805d116599c41c45b775864f612f6",
)

GO_INSTALLER = struct(
    revision = "1.13.5",
    sha256 = "512103d7ad296467814a6e3f635631bd35574cab3369a97a323c9a585ccaa569",
)

JAVA_DEBS_TARBALL = struct(
    revision = "1576656348",
    sha256 = "b63166d0c803f7665888f8625b9eb93b0a57741495eaeb7cd8c508457e460072",
)

CACERTS = struct(
    revision = "1576656348",
    sha256 = "2f37dde2bdb48dfab5ce5c237446f706e283febef4bf916203d1db5789818df8",
)

PYTHON_RBE_DEBS_TARBALL = struct(
    revision = "1575360273",
    sha256 = "7b5776f7a6fbd06a598d70a99bb078473bc395a6d761eacd81f03ec3905a5e91",
)

RBE_TOOLS_DEBS_TARBALL = struct(
    revision = "1576051589",
    sha256 = "707dde619ff3e235420897d0ccd7e6467c533fcd75671aecda1c11fbe2bc16e6",
)
