# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

IMAGE = struct(
    sha256 = "sha256:48e6eb686514d3cb1cbc6dbd874ff93154e8cf15d17123e8f1d521437cd5f93e",
)

PY3_IMAGE = struct(
    sha256 = "sha256:c3280f64c5b329adcfbb66dd20874e49ddb078178f9012278ac02552c6d7f43e",
)

CLANG_INSTALLER = struct(
    revision = "r366207",
    sha256 = "ab5ca3fa052cd164904bf1c2da143c23ca309194a33b98793f08d11b6c104c5b",
)

LIBCXX_INSTALLER = struct(
    revision = "r366207",
    sha256 = "abffabe8993c9de015701c0ae9ef3999a748599145617450001fc80ffc39e2d7",
)

CLANG_DEBS_TARBALL = struct(
    revision = "1567494175",
    sha256 = "15eb744c43d40becb7983f680481042acf16da9f18f394882bf9d4515e2a77f3",
)

GO_INSTALLER = struct(
    revision = "1.13",
    sha256 = "68a2297eb099d1a76097905a2ce334e3155004ec08cdea85f24527be3c48e856",
)

OPENJDK_INSTALLER = struct(
    revision = "11.29.3-ca-jdk11.0.2/zulu11.29.3-ca-jdk11.0.2-linux_x64-allmodules-90755145cb6e6418584d8603cd5fa9afbb30aecc-1549209950",
    sha256 = "460d8a4f0c0204160b48086e341b22943c9cca471b195340e75b38ae9eb33c1c",
)

OPENJDK_SRC = struct(
    revision = "11.31.11-ca-jdk11.0.3/zsrc11.31.11-jdk11.0.3",
    sha256 = "65afc25dd914a094e25b1f804160bb20849f923d9a4b7d989f885558922e8182",
)

JAVA_DEBS_TARBALL = struct(
    revision = "1568098912",
    sha256 = "9053599b705729ea496da822674f0ef77d746ea55234993e422f5850b22becd1",
)

CACERTS = struct(
    revision = "1568098912",
    sha256 = "a86c423b8c5eefbb2708cb4e4081a0084811d2f966ec53719ba68afaa779441a",
)

PYTHON_RBE_DEBS_TARBALL = struct(
    revision = "1568098912",
    sha256 = "a1119408a53fd5c703d68c77bcc2afd239e06872ae855b57581ca7da72c17c56",
)

RBE_TOOLS_DEBS_TARBALL = struct(
    revision = "1568271705",
    sha256 = "ead6ee78b6cc6c97d4cf9c924657ff9597e70223327f98728070c231d22f961f",
)
