# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

IMAGE = struct(
    sha256 = "sha256:c685c61909fef347c1896b269e2886083c04776698522aefff52c680d6bfe14a",
)

PY3_IMAGE = struct(
    sha256 = "sha256:10aa536017a65779b5e6c27bde4f89c7de4516152c4caf56a7379252720548d4",
)

CLANG_INSTALLER = struct(
    revision = "c47f971694be0159ffddfee8a75ae515eba91439",
    sha256 = "88a88af3c0e7474ef7ff2ff04b15b46bb3ac97001149e00257bea376e234f411",
)

LIBCXX_INSTALLER = struct(
    revision = "c47f971694be0159ffddfee8a75ae515eba91439",
    sha256 = "f9f4758163e9c05245bbc16e7bddb907c83973fb0c540fa93178a2c7119dea63",
)

CLANG_DEBS_TARBALL = struct(
    revision = "1586243040",
    sha256 = "047f399d6626fa70633a817973334f8ae45e57b6fcf1ab1a12cd16fc15a48861",
)

GO_INSTALLER = struct(
    revision = "1.14.2",
    sha256 = "6272d6e940ecb71ea5636ddb5fab3933e087c1356173c61f4a803895e947ebb3",
)

JAVA_DEBS_TARBALL = struct(
    revision = "1587625317",
    sha256 = "0f8f9b45b37cf08a9d8cd09a04b978d907a356e70404fbc36d985327cb1f1bac",
)

CACERTS = struct(
    revision = "1587625317",
    sha256 = "a7ec2f45baf194e76860f4c6825942a7b056a2108eccb9fffe358c313e0c955b",
)

PYTHON_RBE_DEBS_TARBALL = struct(
    revision = "1587538942",
    sha256 = "121da08475df7d6fe6998c3f991f2458144d938d207b80bbeb35140f1bbf1f38",
)

RBE_TOOLS_DEBS_TARBALL = struct(
    revision = "1587538942",
    sha256 = "82398ad653227aa1327c1a686a16f2a270c058afef841321aadd3d343fff0045",
)
