# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "e2e_test_ubuntu1604_rbe_staging")

load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
)

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "7d453450e1eb70e238eea6b31f4115607ec1200e91afea01c25f9804f37e39c8",
    strip_prefix = "rules_docker-0.10.0",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.10.0/rules_docker-v0.10.0.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

http_archive(
    name = "bazel_toolchains",
    sha256 = "9ee1e5c5f89100adea6656adef7c0137abcab268c2c3d6184e95f5b8264339d0",
    strip_prefix = "bazel-toolchains-b71837681128e2a834814a3d0bf8c3213a3f2718",
    urls = ["https://github.com/bazelbuild/bazel-toolchains/archive/b71837681128e2a834814a3d0bf8c3213a3f2718.tar.gz"],
)

# Used by FUS to run the metadata rules from bazel-toolchains.
load("@bazel_toolchains//repositories:repositories.bzl", bazel_toolchains_repos = "repositories")

bazel_toolchains_repos()

load("@bazel_toolchains//repositories:go_repositories.bzl", bazel_toolchains_go_repos = "go_deps")

bazel_toolchains_go_repos()

http_archive(
    name = "bazel_skylib",
    # Commit c00ef493869e2966d47508e8625aae723a4a3054 of 2018-12-10
    sha256 = "7363ae6721c1648017e23a200013510c9e71ca69f398d52886ee6af7f26af436",
    strip_prefix = "bazel-skylib-c00ef493869e2966d47508e8625aae723a4a3054",
    urls = ["https://github.com/bazelbuild/bazel-skylib/archive/c00ef493869e2966d47508e8625aae723a4a3054.tar.gz"],
)

load("//base_layer:deps.bzl", ubuntu1604_base_deps = "deps")

ubuntu1604_base_deps()

load("//clang_layer:deps.bzl", clang_deps = "deps")

clang_deps()

load("//java_layer:deps.bzl", java8_deps = "deps")

java8_deps()

load("//go_layer:deps.bzl", go_deps = "deps")

go_deps()

load("//python_rbe_layer:deps.bzl", python_rbe_deps = "deps")

python_rbe_deps()

load("//rbe_tools_layer:deps.bzl", rbe_tools_deps = "deps")

rbe_tools_deps()
