# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 21600s
options:
    machineType: "N1_HIGHCPU_32"

steps:
# Step: print the bazel version for record
  - name: "l.gcr.io/google/bazel"
    args: ["version"]
    id: "version"
    waitFor: ["-"]   # wait for nothing - start immediately

# Pull the semantic checker image used by the //:configs-test target.
  - name: gcr.io/cloud-builders/docker
    args: ["pull", "gcr.io/asci-toolchain/container_release_tools/dependency_update/validators/semantics:latest"]
    id: "pull_validator"
    waitFor: ["-"]   # wait for nothing - start immediately

# Step: Clone a simple project to /project_src folder to be used as the
# testing project for the new Bazel container.
  - name: "l.gcr.io/google/bazel"
    entrypoint: "git"
    args: ["clone", "https://github.com/bazelbuild/bazel.git", "/project_src"]
    volumes:
    - name: "vol1"
      path: "/project_src"
    id: "clone-project"
    waitFor: ["-"]   # wait for nothing - start immediately

# Step: copy the bazel project into a separate dir to run repro tests in parallel.
  - name: "l.gcr.io/google/bazel"
    entrypoint: "sh"
    args: ["-c", "cp -a ubuntu1604_bazel /repro_test/ubuntu1604_bazel"]
    volumes:
      - name: "repro_vol"
        path: "/repro_test"
    id: "copy-to-reproduce"
    waitFor: ["-"]   # wait for nothing - start immediately

# Step: build the image
  - name: "l.gcr.io/google/bazel"
    # Set Bazel output_base to /workspace, which is a mounted directory on Google Cloud Builder.
    # This is to make sure Bazel generated files can be accessed by multiple containers.
    args: ["--output_base=/workspace/output_base", "run", "//:image"]
    # This is needed for GCB to correctly build/test targets in the Bazel project.
    dir: "ubuntu1604_bazel"
    id: "container-build"
    waitFor: ["version"]

# Step: run structure tests on the new image
# We use container_test rule, which is a Bazel wrapper of container_structure_test.
# https://github.com/bazelbuild/rules_docker/blob/master/contrib/test.bzl
  - name: "l.gcr.io/google/bazel"
    args: ["--output_base=/workspace/output_base", "test", "//:image-test", "//:configs_test", "--test_output=errors"]
    # This is needed for GCB to correctly build/test targets in the Bazel project.
    dir: "ubuntu1604_bazel"
    id: "structure-test"
    waitFor: ["pull_validator", "container-build"]

# Step: run reproduction tests on the new image
  - name: "l.gcr.io/google/bazel"
    args: ["--output_base=/repro_test/output_base", "test", "//:img_repro_test", "--test_output=errors"]
    dir: "/repro_test/ubuntu1604_bazel"
    volumes:
      - name: "repro_vol"
        path: "/repro_test"
    id: "repro-test"
    waitFor: ["version", "copy-to-reproduce"]

# Step: `bazel build` the testing project in the new container.
  - name: "bazel:image"
    entrypoint: "bazel"
    args: ["build", "//src:bazel"]
    volumes:
    - name: "vol1"
      path: "/project_src"
    dir: "/project_src"
    id: "integration-test"
    waitFor: ["container-build", "clone-project"]

# Step: tag the image with `latest` at final location.
  - name: "l.gcr.io/google/bazel"
    entrypoint: "docker"
    args: ["tag", "bazel:image", "${_IMG_DEST}:latest"]
    id: "container-tag-latest"
    waitFor: ["structure-test", "repro-test", "integration-test"]

# Step: get the Bazel version from the new container to use as the tag.
  - name: "bazel:image"
    entrypoint: "sh"
    args: ["-c", "bazel version | grep 'Build label' | cut -d ':' -f2 | xargs > /workspace/bazel_version"]
    id: "get-version"
    waitFor: ["structure-test", "repro-test", "integration-test"]

# Step: tag the image with Bazel version at final location.
  - name: "l.gcr.io/google/bazel"
    entrypoint: "sh"
    args: ["-c", "docker tag bazel:image ${_IMG_DEST}:$(cat /workspace/bazel_version)"]
    id: "container-tag-version"
    waitFor: ["get-version"]

# Step: tag the image with Bazel version at backup location.
  - name: "l.gcr.io/google/bazel"
    entrypoint: "sh"
    args: ["-c", "docker tag bazel:image ${_IMG_BACKUP_DEST}:$(cat /workspace/bazel_version)"]
    id: "backup-container-tag"
    waitFor: ["get-version"]

substitutions:
    # Default values for substitution variables.
    _IMG_DEST: gcr.io/asci-toolchain/nosla-ubuntu16-04-bazel
    _IMG_BACKUP_DEST: gcr.io/asci-toolchain-backup/nosla-ubuntu16-04-bazel

# Push the new image and its backup.
# Push by using the `images` field here so they will show up in the build results
# or the GCB Build information page.
# https://cloud.google.com/cloud-build/docs/configuring-builds/store-images-artifacts
images:
  - "${_IMG_DEST}"
  - "${_IMG_BACKUP_DEST}"
