# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "ubuntu1604_webtest")

load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
)
load(":revisions.bzl", "LAYER_DEFINITIONS")

http_archive(
    name = "bazel_toolchains",
    sha256 = "322ef052f15d61fdda3ff5c7be4b03d24e6543320b3b4b41da307aebd75b3c20",
    strip_prefix = "bazel-toolchains-ae9c35af59cfe8af4a631550c0c8d37ff7f4e7da",
    urls = ["https://github.com/bazelbuild/bazel-toolchains/archive/ae9c35af59cfe8af4a631550c0c8d37ff7f4e7da.tar.gz"],
)

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "9fec5e921ca318736fb25acdfdc9a5b425837790c08a525398908b5f8951190d",
    strip_prefix = "rules_docker-8dda5776426f8c742f0bfc230fa455c841afec83",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/8dda5776426f8c742f0bfc230fa455c841afec83.tar.gz"],
)

http_archive(
    name = "base_images_docker",
    sha256 = "0319ed0e058ec57cb15240cad44b52743b68239e5875fa41db51a6f6ac8e67be",
    strip_prefix = "base-images-docker-d6f2757c3c48bd6c08e6484d02b84ed123d50ffa",
    urls = ["https://github.com/GoogleContainerTools/base-images-docker/archive/d6f2757c3c48bd6c08e6484d02b84ed123d50ffa.tar.gz"],
)

http_archive(
    name = "layer_definitions",
    sha256 = LAYER_DEFINITIONS.sha256,
    strip_prefix = "layer-definitions-" + LAYER_DEFINITIONS.commit,
    urls = ["https://github.com/GoogleCloudPlatform/layer-definitions/archive/" + LAYER_DEFINITIONS.commit + ".tar.gz"],
)

http_archive(
    name = "bazel_skylib",
    # Commit c00ef493869e2966d47508e8625aae723a4a3054 of 2018-12-10
    sha256 = "7363ae6721c1648017e23a200013510c9e71ca69f398d52886ee6af7f26af436",
    strip_prefix = "bazel-skylib-c00ef493869e2966d47508e8625aae723a4a3054",
    urls = ["https://github.com/bazelbuild/bazel-skylib/archive/c00ef493869e2966d47508e8625aae723a4a3054.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load("@layer_definitions//layers/ubuntu1604/base:deps.bzl", ubuntu1604_base_deps = "deps")

ubuntu1604_base_deps()

load("@layer_definitions//layers/ubuntu1604/clang:deps.bzl", clang_deps = "deps")

clang_deps()

load("@layer_definitions//layers/ubuntu1604/java:deps.bzl", java8_deps = "deps")

java8_deps()

load("@layer_definitions//layers/ubuntu1604/python_rbe:deps.bzl", python_rbe_deps = "deps")

python_rbe_deps()

load("@layer_definitions//layers/ubuntu1604/rbe_tools:deps.bzl", rbe_tools_deps = "deps")

rbe_tools_deps()

load("@layer_definitions//layers/ubuntu1604/webtest:deps.bzl", webtest_deps = "deps")

webtest_deps()

# Load python & pip dependencies needed by by the @base_images_docker//package_mangers
# package.
http_archive(
    name = "io_bazel_rules_python",
    sha256 = "9a3d71e348da504a9c4c5e8abd4cb822f7afb32c613dc6ee8b8535333a81a938",
    strip_prefix = "rules_python-fdbb17a4118a1728d19e638a5291b4c4266ea5b8",
    urls = ["https://github.com/bazelbuild/rules_python/archive/fdbb17a4118a1728d19e638a5291b4c4266ea5b8.tar.gz"],
)

load("@io_bazel_rules_python//python:pip.bzl", "pip_import", "pip_repositories")

pip_repositories()

pip_import(
    name = "pip_deps",
    requirements = "@base_images_docker//package_managers:requirements-pip.txt",
)

load("@pip_deps//:requirements.bzl", "pip_install")

pip_install()
